### ISSUE TITLE
Update the website

### ISSUE THREAD

**Issue by Ms2ger** [w3c/wasm-wg#3]
At least
- the chair is out of date
- there's a link to the discontinued "unitas" service
- there's a link to the obsolete testthewebforward.org website
- the link to the charter is out of date
- the description of WebAssembly as "We make rocket go faster." could perhaps be improved
- a link to https://webassembly.org/ would be helpful
- links to the TR and ED specifications would be helpful

@ericprud

**Comment by ericprud** [comment]
I updated index.html and https://github.com/w3c/wasm-wg/blob/gh-pages/README.md .
We should have a new charter in a couple weeks but I think I hit the rest of the punch list.

**Comment by Ms2ger** [comment]
Thank you!

**Comment by ericprud** [comment]
I think I'd hit everything before. Feel free to re-open if I am or might be wrong.
